name: Release

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
            pull-requests: write

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Build with Turbopack
              run: pnpm turbo build

            - name: Create Release Pull Request or Publish
              uses: changesets/action@v1
              with:
                  publish: pnpm release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
